### ISSUE TITLE
Tracking backend implementation

### ISSUE THREAD

**Issue by dmitlenko** [dmitlenko/groceryguardian-x#9]
- [x] Create a model for storing product history information (e.g., price, name, etc.) 
- [x] Create a model to assign a specific product to a user 

- Create endpoints: 
  - [x] to retrieve the current items tracked for the current user; 
  - [x] to get the history of a particular item; 
  - [x] to get the details of a particular item; 

- [x] Create a background task to update information about active products and save the history
